#
# Module manifest for module 'VMware.VimAutomation.Cis.Core'
#
# Generated by: "VMware"
#
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'VMware.VimAutomation.Cis.Core.Commands.dll'

# Version number of this module.
ModuleVersion = '6.0.0.0'

# ID used to uniquely identify this module
GUID = '1d5324f6-fb80-495c-9c3e-bd2ff65572cf'

# Author of this module
Author = '"VMware"'

# Company or vendor of this module
CompanyName = 'VMware, Inc.'

# Copyright statement for this module
Copyright = 'Copyright (c) 2015 VMware, Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This Windows PowerShell module contains PowerCLI Cloud Infrastructure Suite cmdlets.'

# Minimum version of the Windows PowerShell engine required by this module
#PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
#PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
#PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
#DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
#CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
#ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('PowerCLI.ViCore')

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'VMware.VimAutomation.Cis.Core.Commands.dll',
    'VMware.VimAutomation.Cis.Core.Impl.dll'
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @('Initialize-VMware_VimAutomation_Cis.ps1')

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('VMware.VimAutomation.Cis.Core.Format.ps1xml')

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules= @('VMware.VimAutomation.Cis.Core.ps1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList =	''

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''
}