#
# Module manifest for module 'PowerCLI.ViCore'
#
# Generated by: adatanasov
#
# Generated on: 4/13/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VMware.VimAutomation.ViCore.Cmdlets.dll'

# Version number of this module.
ModuleVersion = '1.21'

# ID used to uniquely identify this module
GUID = '30e1825e-2c87-4295-8904-96e5b731e1f8'

# Author of this module
Author = 'VMware'

# Company or vendor of this module
CompanyName = 'VMware, Inc.'

# Copyright statement for this module
Copyright = '(c) 2016 VMware, Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerCLI commands for automation of VMware virtual infrastructure products.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
   "System.Private.ServiceModel.dll",
   "ICSharpCode.SharpZipLib.Tar.dll",
   "VMware.AspNet.WebApi.Client.dll",
   "VimService.dll",
   "VMware.Binding.Wcf.dll",
   "VMware.Binding.Ls2.dll",
   "VMware.Vim.dll",
   "InternalVimService50.dll",
   "InventoryService55.dll",
   "VMware.VimAutomation.Sdk.Types.dll",
   "VMware.VimAutomation.Sdk.Util10.dll",
   "VMware.VimAutomation.Sdk.Util10Ps.dll",
   "VMware.VimAutomation.Sdk.Interop.dll",
   "VMware.VimAutomation.Common.Types.dll",
   "VMware.VimAutomation.Common.Util10.dll",
   "VMware.VimAutomation.Common.Util10Ps.dll",
   "VMware.VimAutomation.Common.Interop.dll",
   "VMware.VimAutomation.ViCore.Types.dll",
   "VMware.VimAutomation.ViCore.Util10.dll",
   "VMware.VimAutomation.ViCore.Util10Ps.dll",
   "VMware.VimAutomation.ViCore.Interop.dll",
   "VMware.VimAutomation.ViCore.Impl.dll",
   "VMware.VimAutomation.Vds.Types",
   "VMware.VimAutomation.Vds.Interop",
   "VMware.VimAutomation.Vds.Impl",
   "log4net",
   "phclient",
   "VMware.VimAutomation.Ceip"
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('Initialize.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('VMware.VimAutomation.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

